package pgxgen

import (
	"fmt"
)

const headerFmt = `
package %s

// Generated by pgxgen (see %s)

`

func genHeader(f *File) string {
	return fmt.Sprintf(headerFmt, f.Pkg, f.File.Path)
}

func genImports(f *File, stdImports, otherImports map[string]string) string {
	if len(stdImports) == 0 && len(otherImports) == 0 {
		return ""
	}
	out := "import (\n"
	for path, _ := range stdImports {
		out += fmt.Sprintf("\"%s\"\n", path)
	}
	if len(otherImports) != 0 {
		out += "\n"
	}
	for path, name := range otherImports {
		if name != "" {
			out += name + " "
		}
		out += fmt.Sprintf("\"%s\"\n", path)
	}
	out += ")\n\n"
	return out
}
