package pgxgen

var OidNames = map[string]string{
	"bool":          "Bool",
	"int2":          "Int2",
	"int4":          "Int4",
	"int8":          "Int8",
	"float4":        "Float4",
	"float8":        "Float8",
	"bytea":         "Bytea",
	"text":          "Text",
	"varchar":       "Varchar",
	"date":          "Date",
	"timestampTz":   "TimestampTz",
	"timestamp":     "Timestamp",
	"[]bool":        "BoolArray",
	"[]int2":        "Int2Array",
	"[]int4":        "Int4Array",
	"[]int8":        "Int8Array",
	"[]float4":      "Float4Array",
	"[]float8":      "Float8Array",
	"[]text":        "TextArray",
	"[]varchar":     "VarcharArray",
	"[]timestamp":   "TimestampArray",
	"[]timestampTz": "TimestampTzArray",
	"hstore":        "Hstore",
}

var BinaryFmtOids = map[string]bool{
	"Bool":             true,
	"Bytea":            true,
	"Int2":             true,
	"Int4":             true,
	"Int8":             true,
	"Float4":           true,
	"Float8":           true,
	"TimestampTz":      true,
	"TimestampTzArray": true,
	"Timestamp":        true,
	"TimestampArray":   true,
	"BoolArray":        true,
	"Int2Array":        true,
	"Int4Array":        true,
	"Int8Array":        true,
	"Float4Array":      true,
	"Float8Array":      true,
	"TextArray":        true,
	"VarcharArray":     true,
	"Oid":              true,
}
